name: AvatarSettingsHitAndTouchDetectionMode
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: UseParts
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: UseCollider
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
