name: AvatarSettingsAccessoryLimitMethod
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: Scale
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: Remove
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
