name: AvatarSettingsCustomClothingMode
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: PlayerChoice
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: CustomClothing
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
