name: AvatarSettingsLegacyCollisionMode
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: R6Colliders
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: InnerBoxColliders
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
