name: AvatarSettingsJumpMode
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: JumpHeight
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: JumpPower
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
