name: AvatarSettingsCustomBodyType
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: AvatarReference
    summary: ''
    value: 0
    tags: []
    deprecation_message: ''
  - name: BundleId
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
