name: ProductPurchaseChannel
type: enum
summary: ''
description: ''
code_samples: []
tags: []
deprecation_message: ''
items:
  - name: InExperience
    summary: ''
    value: 1
    tags: []
    deprecation_message: ''
  - name: ExperienceDetailsPage
    summary: ''
    value: 2
    tags: []
    deprecation_message: ''
