name: ChatInputBarConfiguration
type: class
category:
memory_category: Instances
summary: |
  Configures properties of the default chat input bar.
description: |
  Configures properties of the default chat input bar.

  It is parented to `Class.TextChatService`.
code_samples: []
inherits:
  - TextChatConfigurations
tags:
  - NotCreatable
deprecation_message: ''
properties:
  - name: ChatInputBarConfiguration.AbsolutePosition
    summary: |
      Describes the actual screen position of the default chat input bar in
      pixels.
    description: |
      Read-only property that provides the screen position of the default chat
      input bar in pixels. Behaves similarly to
      `Class.GuiBase2d.AbsolutePosition`.
    code_samples: []
    type: Vector2
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: Unsafe
    category: Data
    serialization:
      can_load: false
      can_save: false
  - name: ChatInputBarConfiguration.AbsoluteSize
    summary: |
      Describes the actual screen size of the default chat input bar in pixels.
    description: |
      Read-only property that provides the screen size of the default chat input
      bar in pixels. Behaves similarly to `Class.GuiBase2d.AbsoluteSize`.
    code_samples: []
    type: Vector2
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: Unsafe
    category: Data
    serialization:
      can_load: false
      can_save: false
  - name: ChatInputBarConfiguration.AutocompleteEnabled
    summary: |
      Determines whether to enable autocomplete for the chat input bar.
    description: |
      Determines whether to enable autocomplete for the chat input bar. Set to
      false to disable autocomplete.
    code_samples: []
    type: bool
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Behavior
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.BackgroundColor3
    summary: |
      Determines the background color of the default chat input bar.
    description: |
      Determines the background color of the default chat input bar. Default
      value is `Datatype.Color3|Color3.new(25,27,29)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.BackgroundTransparency
    summary: |
      Determines the background transparency of the default chat input bar.
    description: |
      Determines the background transparency of the default chat input bar as a
      number between 0 and 1. This value is multiplied with the user's
      `Class.GuiService.PreferredTransparency` to create the effective
      background transparency used by the chat input bar, which may be more
      opaque than this value set here. Default value is 0.2.
    code_samples: []
    type: double
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.Enabled
    summary: |
      Determines whether to show the default chat input bar.
    description: |
      Determines whether to show the default chat input bar.

      Set to false to hide the default chat input bar.
    code_samples: []
    type: bool
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Behavior
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.FontFace
    summary: |
      Determines the font used to render text in the default chat input bar.
    description: |
      Determines the font used to render text in the default chat input bar.
    code_samples: []
    type: Font
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.IsFocused
    summary: |
      Describes if the default chat input bar is focused or not.
    description: |
      Indicates whether the default chat input bar is focused or not. Useful for
      firing property changed events so you can implement callback functions
      that respond to changes in the input bar's focus state.
    code_samples:
      - ChatInputBarConfiguration-Typing-Indicator
    type: bool
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: Unsafe
    category: Data
    serialization:
      can_load: false
      can_save: false
  - name: ChatInputBarConfiguration.KeyboardKeyCode
    summary: |
      Determines an additional key users can press to trigger focusing on the
      default chat input bar.
    description: |
      Determines an additional key users can press to trigger focusing on the
      default chat input bar. Useful when you want to have an extra hotkey for
      focusing in addition to the "/" key.
    code_samples: []
    type: KeyCode
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Behavior
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.PlaceholderColor3
    summary: |
      Determines the color of the text of the placeholder text in the default
      chat input bar.
    description: |
      Determines the color of the text of the placeholder text in the default
      chat input bar. Default value is
      `Datatype.Color3|Color3.new(178, 178, 178)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.TargetTextChannel
    summary: |
      A reference to the target `Class.TextChannel`.
    description: |
      A reference to the target `Class.TextChannel`.

      Determines which `Class.TextChannel` to use when the user sends a message
      with the default chat input bar.
    code_samples: []
    type: TextChannel
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.TextBox
    summary: |
      A reference to a designated `Class.TextBox` Instance that sends messages
      on behalf of the user. This property only accepts TextBox instances.
    description: |
      A reference to a designated `Class.TextBox` Instance that sends messages
      on behalf of the user. This property only accepts TextBox instances.

      You can use it to further integrate your custom chat input bar UI into
      your experience by freely manipulating appearance, location, and layout.
      When opting to set this property to a custom TextBox, you don't need to
      write any code for the following behavior:

      - When a user types a message and presses `Enum.KeyCode.Return`, the
        message will be sent to
        `Class.ChatInputBarConfiguration.TargetTextChannel`.
      - When a message is sent, `Class.TextBox.Text` will automatically clear.

      For security, some limitations are imposed on the TextBox when it is
      promoted to `Class.ChatInputBarConfiguration.TextBox`. Lua code will not
      be able to:

      - Change the `Class.TextBox.Text` property.
      - Use the `Class.TextBox.CaptureFocus` or `Class.TextBox.ReleaseFocus`
        methods.
    code_samples: []
    type: TextBox
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: false
  - name: ChatInputBarConfiguration.TextColor3
    summary: |
      Determines the color of the text in default chat input bar.
    description: |
      Determines the color of the text in default chat input bar. Default value
      is `Datatype.Color3|Color3.new(255, 255, 255)` (white).
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.TextSize
    summary: |
      Determines the size of the text in default chat input bar.
    description: |
      Determines the size of the text in default chat input bar. Default value
      is 14.
    code_samples: []
    type: int64
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.TextStrokeColor3
    summary: |
      Determines the color of the text stroke of text in default chat input bar.
    description: |
      Determines the color of the text stroke of text in default chat input bar.
      Default value is `Datatype.Color3|Color3.new(0, 0, 0)` (black).
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
  - name: ChatInputBarConfiguration.TextStrokeTransparency
    summary: |
      Determines the transparency of the text stroke of text in default chat
      input bar.
    description: |
      Determines the color of the text stroke of text in default chat input bar.
      Default value is 0.5.
    code_samples: []
    type: double
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
methods: []
events: []
callbacks: []
