name: ConfigService
type: class
category:
memory_category: Instances
summary: ''
description: ''
code_samples: []
inherits:
  - Instance
tags:
  - NotCreatable
  - Service
  - NotReplicated
deprecation_message: ''
properties: []
methods:
  - name: ConfigService:GetConfigAsync
    summary: ''
    description: ''
    code_samples: []
    parameters: []
    returns:
      - type: ConfigSnapshot
        summary: ''
    tags:
      - Yields
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
  - name: ConfigService:GetConfigForPlayerAsync
    summary: ''
    description: ''
    code_samples: []
    parameters:
      - name: player
        type: Player
        default:
        summary: ''
    returns:
      - type: ConfigSnapshot
        summary: ''
    tags:
      - Yields
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
events: []
callbacks: []
