name: DebugSettings
type: class
category: Settings
memory_category: Instances
summary: |
  Collection of various developer-facing diagnostics information.
description: |
  The DebugSettings allows you to view diagnostics information regarding Roblox.
  It is labeled as **Diagnostics** in the Roblox Studio Settings menu.
code_samples:
inherits:
  - Instance
tags:
  - NotCreatable
  - Settings
  - NotBrowsable
deprecation_message: ''
properties:
  - name: DebugSettings.DataModel
    summary: |
      Describes whether a `Class.DataModel` is actively in memory, as an integer
      (where 1 = true, and 0 = false).
    description: |
      Describes whether a `Class.DataModel` is actively in memory, as an integer
      (where 1 = true, and 0 = false).
    code_samples:
    type: int
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Performance
    serialization:
      can_load: false
      can_save: true
  - name: DebugSettings.InstanceCount
    summary: |
      The number of instances active in the simulation.
    description: |
      The number of instances active in the simulation.
    code_samples:
    type: int
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Performance
    serialization:
      can_load: false
      can_save: true
  - name: DebugSettings.IsScriptStackTracingEnabled
    summary: |
      Whether or not a stacktrace is displayed in the output for an error.
    description: |
      Whether or not a stacktrace is displayed in the output for an error.
    code_samples:
    type: bool
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Errors
    serialization:
      can_load: true
      can_save: true
  - name: DebugSettings.JobCount
    summary: |
      Returns the number of internal DataModel jobs actively being processed.
    description: |
      Returns the number of internal DataModel jobs actively being processed.
    code_samples:
    type: int
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Performance
    serialization:
      can_load: false
      can_save: true
  - name: DebugSettings.PlayerCount
    summary: |
      The number of players currently in the active game-instance.
    description: |
      The number of players currently in the active game-instance.
    code_samples:
    type: int
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Performance
    serialization:
      can_load: false
      can_save: true
  - name: DebugSettings.ReportSoundWarnings
    summary: |
      Whether or not sound warnings should be reported.
    description: |
      Whether or not sound warnings should be reported.
    code_samples:
    type: bool
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Errors
    serialization:
      can_load: true
      can_save: true
  - name: DebugSettings.RobloxVersion
    summary: |
      The current client version of Roblox. Can also be retrieved by using the
      version() function.
    description: |
      The current client version of Roblox. Can also be retrieved by using the
      version() function.
    code_samples:
    type: string
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Profile
    serialization:
      can_load: false
      can_save: true
  - name: DebugSettings.TickCountPreciseOverride
    summary: |
      Sets the internal sampling method used to measure elapsed time with
      consistency across platforms.
    description: |
      Sets the internal sampling method used to measure elapsed time with
      consistency across platforms.
    code_samples:
    type: TickCountSampleMethod
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Benchmarking
    serialization:
      can_load: true
      can_save: true
methods: []
events: []
callbacks: []
