name: GameSettings
type: class
memory_category: Instances
summary: |
  A container for miscellaneous in-game options.
description: |
  Various miscellaneous in-game options.
code_samples: []
inherits:
  - Instance
tags:
  - NotCreatable
  - Settings
  - NotReplicated
  - NotBrowsable
deprecation_message: ''
properties:
  - name: GameSettings.VideoCaptureEnabled
    summary: |
      Toggles whether or not video capture is enabled.
    description: |
      Toggles whether or not video capture is enabled.
    code_samples: []
    type: boolean
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Video
    serialization:
      can_load: true
      can_save: true
    capabilities: []
    writeCapabilities: []
  - name: GameSettings.VideoRecording
    summary: ''
    description: ''
    code_samples: []
    type: boolean
    tags:
      - NotReplicated
    deprecation_message: ''
    security:
      read: RobloxScriptSecurity
      write: RobloxEngineSecurity
    thread_safety: ReadSafe
    category: Video
    serialization:
      can_load: true
      can_save: false
    capabilities: []
    writeCapabilities: []
methods: []
events: []
callbacks: []
