{
  "openapi": "3.0.0",
  "info": {
    "title": "Cloud API",
    "description": "The Roblox Open Cloud v2 API. This is a subset of endpoints that Roblox\n provides. See https://create.roblox.com/docs/cloud/open-cloud for more\n details.",
    "version": "2.0.0"
  },
  "servers": [
    {
      "url": "https://apis.roblox.com"
    }
  ],
  "paths": {
    "/cloud/v2/creator-store-products": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Creator Store Product",
        "description": "Add a Creator Store product.",
        "operationId": "Cloud_CreateCreatorStoreProduct",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Monetization",
          "methodProperties": {
            "scopes": [
              "creator-store-product:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/CreatorStoreProduct",
            "name": "CreatorStoreProduct"
          }
        }
      }
    },
    "/cloud/v2/creator-store-products/{creator_store_product_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Creator Store Product",
        "description": "Get a Creator Store product.",
        "operationId": "Cloud_GetCreatorStoreProduct",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Monetization",
          "methodProperties": {
            "scopes": [
              "creator-store-product:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/CreatorStoreProduct",
            "name": "CreatorStoreProduct"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Creator Store Product",
        "description": "Update a Creator Store product.",
        "operationId": "Cloud_UpdateCreatorStoreProduct",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Monetization",
          "methodProperties": {
            "scopes": [
              "creator-store-product:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/CreatorStoreProduct",
            "name": "CreatorStoreProduct"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Group",
        "description": "Gets the specified group.",
        "operationId": "Cloud_GetGroup",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/Group",
            "name": "Group"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/join-requests": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Group Join Requests",
        "description": "List join requests under a group.",
        "operationId": "Cloud_ListGroupJoinRequests",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "group:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/GroupJoinRequest",
            "name": "GroupJoinRequest"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/join-requests/{join_request_id}:accept": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Accept Group Join Request",
        "description": "Accepts a join request.",
        "operationId": "Cloud_AcceptGroupJoinRequest",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "group:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/GroupJoinRequest",
            "name": "GroupJoinRequest"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/join-requests/{join_request_id}:decline": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Decline Group Join Request",
        "description": "Declines a join request.",
        "operationId": "Cloud_DeclineGroupJoinRequest",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "group:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/GroupJoinRequest",
            "name": "GroupJoinRequest"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/memberships": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Group Memberships",
        "description": "List group members in a group.",
        "operationId": "Cloud_ListGroupMemberships",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/GroupMembership",
            "name": "GroupMembership"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/memberships/{membership_id}": {
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Group Membership",
        "description": "Updates the group membership for a particular group member. This action\n requires the requester to be able to manage lower ranked members. Guest or\n Owner ranks cannot be assigned, and a requester cannot change their own\n rank.",
        "operationId": "Cloud_UpdateGroupMembership",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "group:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/GroupMembership",
            "name": "GroupMembership"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/roles": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Group Roles",
        "description": "List roles in a group.\n\n The permissions field for roles is viewable based on the requester's access\n and scopes.\n\n Permissions for the guest role are always visible - a scope is not needed.\n\n If the requester is a member of the group and has the `group:read` scope,\n permissions in their role are visible.\n\n If the requester is the owner of the group and has the `group:read` scope,\n permissions in all roles are visible.",
        "operationId": "Cloud_ListGroupRoles",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/GroupRole",
            "name": "GroupRole"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/roles/{role_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Group Role",
        "description": "Get the group role",
        "operationId": "Cloud_GetGroupRole",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/GroupRole",
            "name": "GroupRole"
          }
        }
      }
    },
    "/cloud/v2/groups/{group_id}/shout": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Group Shout",
        "description": "Gets the group shout.\n\n If a guest can view the group shout, this is always retrievable.\n\n If a guest cannot, a member who has the permissions to view the group\n shout, along with the `group:read` scope, will be able to read the group\n shout.",
        "operationId": "Cloud_GetGroupShout",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/GroupShout",
            "name": "GroupShout"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Universe",
        "description": "Gets the specified universe.",
        "operationId": "Cloud_GetUniverse",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/Universe",
            "name": "Universe"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Universe",
        "description": "Updates the specified universe.\n\n This method is guaranteed to return all updated fields.\n This method may additionally return the full resource.",
        "operationId": "Cloud_UpdateUniverse",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Universe",
            "name": "Universe"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Data Stores",
        "description": "Returns a list of data stores.",
        "operationId": "Cloud_ListDataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.control:list"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStore",
            "name": "DataStore"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/entries": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Data Store Entries",
        "description": "Returns a list of entries from a data store.\n\n Only the `path` and `id` fields are populated; use `GetDataStoreEntry`\n to retrieve other fields.\n\n Specify the wildcard scope (`-`) to list entries from all scopes.",
        "operationId": "Cloud_ListDataStoreEntries__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:list"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Data Store Entry",
        "description": "Creates an entry with the provided ID and value.\n\n Returns a 400 Bad Request if the entry exists.",
        "operationId": "Cloud_CreateDataStoreEntry__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:create"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/entries/{entry_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Data Store Entry",
        "description": "Gets the specified entry.\n\n To get the entry at a specific revision, add `@<revisionId>` to the end of\n the path.\n\n For example, to get `my-entry` at the revision ID\n `08DC3D3F43F9FCC1.0000000001.08DC3D3F43F9FCC1.01`, use the path\n `/v2/universes/1234/data-stores/5678/entries/my-entry@08DC3D3F43F9FCC1.0000000001.08DC3D3F43F9FCC1.01`.\n\n If your entry ID contains one or more `@` characters, and you want to get\n the latest version rather than at any specific revisi[...]",
        "operationId": "Cloud_GetDataStoreEntry__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "delete": {
        "tags": [
          "Cloud"
        ],
        "summary": "Delete Data Store Entry",
        "description": "Marks the specified entry for deletion.\n\n Entries are not be deleted immediately; instead, the `state` field will\n be set to `DELETED`. Permanent deletion occurs after 30 days.\n\n On success, returns 200 OK. If the entry doesn't exist, returns\n 404 Not Found.",
        "operationId": "Cloud_DeleteDataStoreEntry__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:delete"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Data Store Entry",
        "description": "Updates the value, attributes, and users of an entry.\n\n Updating specific revisions of the entry is **unsupported**. If you specify\n a revision ID in the path and `allow_missing` is `true`, the update request\n will instead create a new entry with the `@<revisionId>` suffix as part of\n the key.\n\n Partial update is **unsupported**. If attributes or users are not\n provided when updating the value, they will be cleared. Value must always\n be provided when updating an[...]",
        "operationId": "Cloud_UpdateDataStoreEntry__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:update"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/entries/{entry_id}:increment": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Increment Data Store Entry",
        "description": "Increments the value of the specified entry. Both the existing value and\n the increment amount must be integers.\n\n If the entry doesn't exist, creates an entry with the specified value.\n\n Incrementing specific revisions of the entry is **unsupported**. If you\n specify a revision ID in the path, the increment request will create a new\n entry with the `@<revisionId>` suffix as part of the key.\n\n Known issue: the value may be incremented past the valid range of  val[...]",
        "operationId": "Cloud_IncrementDataStoreEntry__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:create",
              "universe-datastores.objects:update"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/entries/{entry_id}:listRevisions": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Data Store Entry Revisions",
        "description": "List revisions of the data store entry.\n\n This method returns partial data store entries.\n\n In particular, only the `path`, `id`, `createTime`, `revisionCreateTime`,\n `revisionId`, `etag`, and `state` fields are populated. Both the `path` and\n `id` fields will have an `@<version>` suffix.\n\n In order to get the full entry at a revision, you can use the provided\n `path` field with the `GetDataStoreEntry` method, i.e. `GET\n /v1/universes/1234/data-stores/5678/entri[...]",
        "operationId": "Cloud_ListDataStoreEntryRevisions__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.versions:list"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/scopes/{scope_id}/entries": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Data Store Entries",
        "description": "Returns a list of entries from a data store.\n\n Only the `path` and `id` fields are populated; use `GetDataStoreEntry`\n to retrieve other fields.\n\n Specify the wildcard scope (`-`) to list entries from all scopes.",
        "operationId": "Cloud_ListDataStoreEntries__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:list"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Data Store Entry",
        "description": "Creates an entry with the provided ID and value.\n\n Returns a 400 Bad Request if the entry exists.",
        "operationId": "Cloud_CreateDataStoreEntry__Using_Universes_DataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:create"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/scopes/{scope_id}/entries/{entry_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Data Store Entry",
        "description": "Gets the specified entry.\n\n To get the entry at a specific revision, add `@<revisionId>` to the end of\n the path.\n\n For example, to get `my-entry` at the revision ID\n `08DC3D3F43F9FCC1.0000000001.08DC3D3F43F9FCC1.01`, use the path\n `/v2/universes/1234/data-stores/5678/entries/my-entry@08DC3D3F43F9FCC1.0000000001.08DC3D3F43F9FCC1.01`.\n\n If your entry ID contains one or more `@` characters, and you want to get\n the latest version rather than at any specific revisi[...]",
        "operationId": "Cloud_GetDataStoreEntry__Using_Universes_DataStores_Scopes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "delete": {
        "tags": [
          "Cloud"
        ],
        "summary": "Delete Data Store Entry",
        "description": "Marks the specified entry for deletion.\n\n Entries are not be deleted immediately; instead, the `state` field will\n be set to `DELETED`. Permanent deletion occurs after 30 days.\n\n On success, returns 200 OK. If the entry doesn't exist, returns\n 404 Not Found.",
        "operationId": "Cloud_DeleteDataStoreEntry__Using_Universes_DataStores_Scopes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:delete"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Data Store Entry",
        "description": "Updates the value, attributes, and users of an entry.\n\n Updating specific revisions of the entry is **unsupported**. If you specify\n a revision ID in the path and `allow_missing` is `true`, the update request\n will instead create a new entry with the `@<revisionId>` suffix as part of\n the key.\n\n Partial update is **unsupported**. If attributes or users are not\n provided when updating the value, they will be cleared. Value must always\n be provided when updating an[...]",
        "operationId": "Cloud_UpdateDataStoreEntry__Using_Universes_DataStores_Scopes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:update"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/scopes/{scope_id}/entries/{entry_id}:increment": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Increment Data Store Entry",
        "description": "Increments the value of the specified entry. Both the existing value and\n the increment amount must be integers.\n\n If the entry doesn't exist, creates an entry with the specified value.\n\n Incrementing specific revisions of the entry is **unsupported**. If you\n specify a revision ID in the path, the increment request will create a new\n entry with the `@<revisionId>` suffix as part of the key.\n\n Known issue: the value may be incremented past the valid range of  val[...]",
        "operationId": "Cloud_IncrementDataStoreEntry__Using_Universes_DataStores_Scopes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.objects:create",
              "universe-datastores.objects:update"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores/{data_store_id}/scopes/{scope_id}/entries/{entry_id}:listRevisions": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Data Store Entry Revisions",
        "description": "List revisions of the data store entry.\n\n This method returns partial data store entries.\n\n In particular, only the `path`, `id`, `createTime`, `revisionCreateTime`,\n `revisionId`, `etag`, and `state` fields are populated. Both the `path` and\n `id` fields will have an `@<version>` suffix.\n\n In order to get the full entry at a revision, you can use the provided\n `path` field with the `GetDataStoreEntry` method, i.e. `GET\n /v1/universes/1234/data-stores/5678/entri[...]",
        "operationId": "Cloud_ListDataStoreEntryRevisions__Using_Universes_DataStores_Scopes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.versions:list"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStoreEntry",
            "name": "DataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/data-stores:snapshot": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Snapshot Data Stores",
        "description": "Takes a new snapshot of the data stores in an experience.\n\n After a snapshot, the next write to every key in the experience will\n create a versioned backup of the previous data, regardless of the time of\n the last write.\n\n In effect, all data current at the time of the snapshot is guaranteed to be\n available as a versioned backup for at least 30 days.\n\n Snapshots can be taken once per UTC day, per experience. If the latest\n snapshot was taken within the same UTC[...]",
        "operationId": "Cloud_SnapshotDataStores",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe-datastores.control:snapshot"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/DataStore",
            "name": "DataStore"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store/queues/{queue_id}/items": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Memory Store Queue Item",
        "description": "Creates a new queue item.\n\n If `ttl` is set, the item will automatically be removed from the queue\n after the time interval specified.\n\n If a numerical `priority` is set, the item will be inserted into the queue\n based on the priority value. The higher the value, the closer to the front\n of the queue the item will be. If priority values are the same then the\n item will be inserted after existing values with the same priority.",
        "operationId": "Cloud_CreateMemoryStoreQueueItem",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.queue:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreQueueItem",
            "name": "MemoryStoreQueueItem"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store/queues/{queue_id}/items:discard": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Discard Memory Store Queue Items",
        "description": "Discards read items from the front of the queue.\n\n Takes a `readId` from a previous `Read` operation.",
        "operationId": "Cloud_DiscardMemoryStoreQueueItems",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.queue:discard"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreQueueItem",
            "name": "MemoryStoreQueueItem"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store/queues/{queue_id}/items:read": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Read Memory Store Queue Items",
        "description": "Returns the specified number of items at the front of the queue.",
        "operationId": "Cloud_ReadMemoryStoreQueueItems",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.queue:dequeue"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreQueueItem",
            "name": "MemoryStoreQueueItem"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store/sorted-maps/{sorted_map_id}/items": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Memory Store Sorted Map Items",
        "description": "Gets and returns items in the map with a given order and filter.",
        "operationId": "Cloud_ListMemoryStoreSortedMapItems",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.sorted-map:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreSortedMapItem",
            "name": "MemoryStoreSortedMapItem"
          }
        }
      },
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Memory Store Sorted Map Item",
        "description": "Creates the specified map item if it doesn't exist.",
        "operationId": "Cloud_CreateMemoryStoreSortedMapItem",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.sorted-map:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreSortedMapItem",
            "name": "MemoryStoreSortedMapItem"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store/sorted-maps/{sorted_map_id}/items/{item_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Memory Store Sorted Map Item",
        "description": "Gets and returns the value of the given key in the map.",
        "operationId": "Cloud_GetMemoryStoreSortedMapItem",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.sorted-map:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreSortedMapItem",
            "name": "MemoryStoreSortedMapItem"
          }
        }
      },
      "delete": {
        "tags": [
          "Cloud"
        ],
        "summary": "Delete Memory Store Sorted Map Item",
        "description": "Deletes the specified item from the map.",
        "operationId": "Cloud_DeleteMemoryStoreSortedMapItem",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.sorted-map:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreSortedMapItem",
            "name": "MemoryStoreSortedMapItem"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Memory Store Sorted Map Item",
        "description": "Updates the specified map item.",
        "operationId": "Cloud_UpdateMemoryStoreSortedMapItem",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store.sorted-map:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStoreSortedMapItem",
            "name": "MemoryStoreSortedMapItem"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/memory-store:flush": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Flush Memory Store",
        "description": "Asynchronously flush all data structures in the universe.",
        "operationId": "Cloud_FlushMemoryStore",
        "x-long-running-operation-parameters": {
          "metadata": {
            "$ref": "#/components/schemas/FlushMemoryStoreMetadata"
          }
        },
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.memory-store:flush"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/MemoryStore",
            "name": "MemoryStore"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/ordered-data-stores/{ordered_data_store_id}/scopes/{scope_id}/entries": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Ordered Data Store Entries",
        "description": "Returns a list of entries from an ordered data store.",
        "operationId": "Cloud_ListOrderedDataStoreEntries",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      },
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Ordered Data Store Entry",
        "description": "Creates an entry with the provided ID and value.\n\n Returns a 400 Bad Request if the entry exists.",
        "operationId": "Cloud_CreateOrderedDataStoreEntry",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/ordered-data-stores/{ordered_data_store_id}/scopes/{scope_id}/entries/{entry_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Ordered Data Store Entry",
        "description": "Gets the specified entry.",
        "operationId": "Cloud_GetOrderedDataStoreEntry",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      },
      "delete": {
        "tags": [
          "Cloud"
        ],
        "summary": "Delete Ordered Data Store Entry",
        "description": "Deletes the specified entry.\n\n On success, returns 200 OK. If the entry doesn't exist, returns\n 404 Not Found.",
        "operationId": "Cloud_DeleteOrderedDataStoreEntry",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Ordered Data Store Entry",
        "description": "Updates the value of an entry.",
        "operationId": "Cloud_UpdateOrderedDataStoreEntry",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/ordered-data-stores/{ordered_data_store_id}/scopes/{scope_id}/entries/{entry_id}:increment": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Increment Ordered Data Store Entry",
        "description": "Increments the value of the specified entry. Both the existing value and\n the increment amount must be integers.\n\n If the entry doesn't exist, creates an entry with the specified value.\n\n Known issue: the value may be incremented past the valid range of  values.\n When this happens, the returned value will be clamped to the valid range,\n but the backend may persist the original value. This behavior is maintained\n for backwards compatibility reasons, but may change [...]",
        "operationId": "Cloud_IncrementOrderedDataStoreEntry",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Data and memory stores",
          "methodProperties": {
            "scopes": [
              "universe.ordered-data-store.scope.entry:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/OrderedDataStoreEntry",
            "name": "OrderedDataStoreEntry"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Place",
        "description": "Gets the specified place.",
        "operationId": "Cloud_GetPlace",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/Place",
            "name": "Place"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Place",
        "description": "Updates the specified place.",
        "operationId": "Cloud_UpdatePlace",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe.place:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Place",
            "name": "Place"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/instances/{instance_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Instance",
        "description": "Gets an instance and its property data.\n\n The maximum supported response data size is 500,000 bytes. If this limit is\n exceeded, the returned `Operation` will be completed with an error result\n that has an error code of `422`.",
        "operationId": "Cloud_GetInstance",
        "x-long-running-operation-parameters": {
          "metadata": {
            "$ref": "#/components/schemas/GetInstanceMetadata"
          }
        },
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe.place.instance:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Instance",
            "name": "Instance"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update Instance",
        "description": "Updates an instance's property data.\n\n When updating a `Script` instance's source property, the maximum supported\n property size is 200,000 bytes after UTF-8 encoding.",
        "operationId": "Cloud_UpdateInstance",
        "x-long-running-operation-parameters": {
          "metadata": {
            "$ref": "#/components/schemas/UpdateInstanceMetadata"
          }
        },
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe.place.instance:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Instance",
            "name": "Instance"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/instances/{instance_id}:listChildren": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Instance Children",
        "description": "Lists an instance's children.\n\n The maximum supported response data size is 500,000 bytes. If this limit is\n exceeded, the returned `Operation` will be completed with an error result\n that has an error code of `422`.",
        "operationId": "Cloud_ListInstanceChildren",
        "x-long-running-operation-parameters": {
          "metadata": {
            "$ref": "#/components/schemas/ListInstanceChildrenMetadata"
          }
        },
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe.place.instance:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Instance",
            "name": "Instance"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/luau-execution-session-tasks": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Luau Execution Session Task",
        "description": "Creates a task but does not wait for the task to complete.\n\n To check whether a task has\n completed, call the `GetLuauExecutionSessionTask` method and inspect the\n `state` field of the returned resource.\n\n Quotas:\n * 5 calls per minute per API key owner\n * 45 calls per minute per IP address",
        "operationId": "Cloud_CreateLuauExecutionSessionTask__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTask",
            "name": "LuauExecutionSessionTask"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/luau-execution-session-tasks/{luau_execution_session_task_id}/logs": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Luau Execution Session Task Logs",
        "description": "Lists log chunks generated by a `LuauExecutionSessionTask`.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_ListLuauExecutionSessionTaskLogs__Using_Universes_Places",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTaskLog",
            "name": "LuauExecutionSessionTaskLog"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{task_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Luau Execution Session Task",
        "description": "Gets information about a task.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_GetLuauExecutionSessionTask__Using_Universes_Places_LuauExecutionSessions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTask",
            "name": "LuauExecutionSessionTask"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{task_id}/logs": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Luau Execution Session Task Logs",
        "description": "Lists log chunks generated by a `LuauExecutionSessionTask`.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_ListLuauExecutionSessionTaskLogs__Using_Universes_Places_LuauExecutionSessions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTaskLog",
            "name": "LuauExecutionSessionTaskLog"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/user-restrictions": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List User Restrictions",
        "description": "List user restrictions for users that have ever been banned in either a\n universe or a specific place.",
        "operationId": "Cloud_ListUserRestrictions__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/user-restrictions/{user_restriction_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get User Restriction",
        "description": "Get the user restriction.",
        "operationId": "Cloud_GetUserRestriction__Using_Universes_Places",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update User Restriction",
        "description": "Update the user restriction.",
        "operationId": "Cloud_UpdateUserRestriction__Using_Universes_Places",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/versions/{version_id}/luau-execution-session-tasks": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create Luau Execution Session Task",
        "description": "Creates a task but does not wait for the task to complete.\n\n To check whether a task has\n completed, call the `GetLuauExecutionSessionTask` method and inspect the\n `state` field of the returned resource.\n\n Quotas:\n * 5 calls per minute per API key owner\n * 45 calls per minute per IP address",
        "operationId": "Cloud_CreateLuauExecutionSessionTask__Using_Universes_Places",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTask",
            "name": "LuauExecutionSessionTask"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/versions/{version_id}/luau-execution-session-tasks/{luau_execution_session_task_id}/logs": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Luau Execution Session Task Logs",
        "description": "Lists log chunks generated by a `LuauExecutionSessionTask`.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_ListLuauExecutionSessionTaskLogs__Using_Universes_Places_Versions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTaskLog",
            "name": "LuauExecutionSessionTaskLog"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/versions/{version_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{task_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Luau Execution Session Task",
        "description": "Gets information about a task.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_GetLuauExecutionSessionTask__Using_Universes_Places_Versions_LuauExecutionSessions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTask",
            "name": "LuauExecutionSessionTask"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/places/{place_id}/versions/{version_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{task_id}/logs": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Luau Execution Session Task Logs",
        "description": "Lists log chunks generated by a `LuauExecutionSessionTask`.\n\n Quotas:\n * 45 calls per minute per API key owner or IP address",
        "operationId": "Cloud_ListLuauExecutionSessionTaskLogs__Using_Universes_Places_Versions_LuauExecutionSessions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Luau execution",
          "methodProperties": {
            "scopes": [
              "universe.place.luau-execution-session:read",
              "universe.place.luau-execution-session:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/LuauExecutionSessionTaskLog",
            "name": "LuauExecutionSessionTaskLog"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/subscription-products/{subscription_product_id}/subscriptions/{subscription_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get Subscription",
        "description": "Get the subscription.\n\n The `universe.subscription-product.subscription:read` scope only allows\n you to get your own subscriptions—or rather, the subscription ID must\n match the user ID that makes the request—so its best use case is with\n OAuth 2.0 authentication rather than an API key. To read all\n subscriptions for a universe, use the `universe:write` scope.",
        "operationId": "Cloud_GetSubscription",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Monetization",
          "methodProperties": {
            "scopes": [
              "universe:write",
              "universe.subscription-product.subscription:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Subscription",
            "name": "Subscription"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/user-restrictions": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List User Restrictions",
        "description": "List user restrictions for users that have ever been banned in either a\n universe or a specific place.",
        "operationId": "Cloud_ListUserRestrictions",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/user-restrictions/{user_restriction_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get User Restriction",
        "description": "Get the user restriction.",
        "operationId": "Cloud_GetUserRestriction__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      },
      "patch": {
        "tags": [
          "Cloud"
        ],
        "summary": "Update User Restriction",
        "description": "Update the user restriction.",
        "operationId": "Cloud_UpdateUserRestriction__Using_Universes",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}/user-restrictions:listLogs": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List User Restriction Logs",
        "description": "List changes to UserRestriction resources within a given universe.\n This includes both universe-level and place-level restrictions.\n\n For universe-level restriction logs, the `place` field will be empty.",
        "operationId": "Cloud_ListUserRestrictionLogs",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "universe.user-restriction:read"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserRestriction",
            "name": "UserRestriction"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}:publishMessage": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Publish Universe Message",
        "description": "Publishes a message to the universe's live servers.\n\n Servers can consume messages via\n [MessagingService](https://create.roblox.com/docs/reference/engine/classes/MessagingService).",
        "operationId": "Cloud_PublishUniverseMessage",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe-messaging-service:publish"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Universe",
            "name": "Universe"
          }
        }
      }
    },
    "/cloud/v2/universes/{universe_id}:restartServers": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Restart Universe Servers",
        "description": "Restarts all active servers for a specific universe if and only if a new\n version of the experience has been published. Used for releasing experience\n updates.",
        "operationId": "Cloud_RestartUniverseServers",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Universes and places",
          "methodProperties": {
            "scopes": [
              "universe:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/Universe",
            "name": "Universe"
          }
        }
      }
    },
    "/cloud/v2/users/{user_id}": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Get User",
        "description": "Gets a user's basic and advanced information.\n\n To access a user's public information, no additional scopes are required.\n\n To access a user's verification status, you need the following scopes:\n * user.advanced.read\n\n To access a user's social account information, you need the following\n scopes:\n * user.social.read",
        "operationId": "Cloud_GetUser",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/User",
            "name": "User"
          }
        }
      }
    },
    "/cloud/v2/users/{user_id}/inventory-items": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "List Inventory Items",
        "description": "List the inventory items in a user's inventory.\n\n The inventory items returned depend on the target user’s choice under\n **Settings > Privacy > Who can see my inventory?**:\n * If the user granted inventory visibility to \"Everyone,\" then any API key\n or OAuth2 token can be used to view the target’s inventory, no matter what\n scopes it has or who created it.\n * If the user has not granted inventory visibility to \"Everyone\":\n   * Their inventory can still be view[...]",
        "operationId": "Cloud_ListInventoryItems",
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/InventoryItem",
            "name": "InventoryItem"
          }
        }
      }
    },
    "/cloud/v2/users/{user_id}/notifications": {
      "post": {
        "tags": [
          "Cloud"
        ],
        "summary": "Create User Notification",
        "description": "Sends a notification to a user.",
        "operationId": "Cloud_CreateUserNotification",
        "x-visibility": "STABLE",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": [
              "user.user-notification:write"
            ]
          },
          "resource": {
            "$ref": "#/components/schemas/UserNotification",
            "name": "UserNotification"
          }
        }
      }
    },
    "/cloud/v2/users/{user_id}:generateThumbnail": {
      "get": {
        "tags": [
          "Cloud"
        ],
        "summary": "Generate User Thumbnail",
        "description": "Generates and returns the URL for the user's avatar thumbnail.",
        "operationId": "Cloud_GenerateUserThumbnail",
        "x-long-running-operation-parameters": {
          "metadata": {
            "$ref": "#/components/schemas/GenerateUserThumbnailMetadata"
          }
        },
        "x-visibility": "BETA",
        "x-roblox-docs": {
          "category": "Users and groups",
          "methodProperties": {
            "scopes": []
          },
          "resource": {
            "$ref": "#/components/schemas/User",
            "name": "User"
          }
        }
      }
    }
  },
  "components": {
  },
  "tags": [
    {
      "name": "Cloud"
    }
  ],
  "x-categories": [
    "Data and memory stores",
    "Luau execution",
    "Monetization",
    "Universes and places",
    "Users and groups"
  ]
}
