name: Quality Checks
description: Reusable action for running the quality checks
inputs:
  BASE_BRANCH:
    description: Base branch
  CHECK_LOCALIZED_CONTENT:
    description: Whether to check localized content
  DELETE_MDX_MISMATCHED_ERROR_ON_FAIL:
    description: Whether to delete localized files with MDX mismatched errors
  CHECK_MARKDOWN_LINT:
    description: Whether to check markdown lint
  CHECK_PROTECTED_FIELDS:
    description: Whether to check protected YAML fields
  CHECK_RELATIVE_LINKS:
    description: Whether to check relative links
  CHECK_RETEXT_ANALYSIS:
    description: Whether to check retext analysis
  CHECK_UNUSED_ASSETS:
    description: Whether to check for unused assets
  COMMIT_HASH:
    description: Commit hash
  EVENT_NAME:
    description: Github event name
  GITHUB_PAT:
    description: Github token
  POST_PULL_REQUEST_COMMENTS:
    description: Whether to post comments on the pull request
  PULL_REQUEST_NUMBER:
    description: Pull request number

runs:
  using: 'composite'
  steps:
    - name: Run quality checks
      shell: bash
      run: |
        echo "Base branch: ${{ inputs.BASE_BRANCH }}"
        echo "Commit hash: ${{ inputs.COMMIT_HASH }}"
        echo "GitHub event name: ${{ inputs.EVENT_NAME }}"
        echo "Pull request number: ${{ inputs.PULL_REQUEST_NUMBER }}"

        if [ "${{ inputs.EVENT_NAME }}" = "pull_request" ] || [ "${{ inputs.EVENT_NAME }}" = "pull_request_target" ]; then
          npm run check -- --files='changed' --postPullRequestComments=${{ inputs.POST_PULL_REQUEST_COMMENTS }}
        elif [ "${{ inputs.EVENT_NAME }}" = "push" ]; then
          npm run check -- --files='last-commit' --postPullRequestComments=false
        elif [ "${{ inputs.EVENT_NAME }}" = "workflow_dispatch" ]; then
          npm run check -- --files='all' --postPullRequestComments=false
        else
          echo "Unknown GitHub event name: ${{ inputs.EVENT_NAME }}"
          exit 1
        fi
      env:
        GITHUB_PAT: ${{ inputs.GITHUB_PAT }}
        BASE_BRANCH: ${{ inputs.BASE_BRANCH }}
        CHECK_LOCALIZED_CONTENT: ${{ inputs.CHECK_LOCALIZED_CONTENT }}
        CHECK_MARKDOWN_LINT: ${{ inputs.CHECK_MARKDOWN_LINT }}
        CHECK_PROTECTED_FIELDS: ${{ inputs.CHECK_PROTECTED_FIELDS }}
        CHECK_RELATIVE_LINKS: ${{ inputs.CHECK_RELATIVE_LINKS }}
        CHECK_RETEXT_ANALYSIS: ${{ inputs.CHECK_RETEXT_ANALYSIS }}
        CHECK_UNUSED_ASSETS: ${{ inputs.CHECK_UNUSED_ASSETS }}
        DELETE_MDX_MISMATCHED_ERROR_ON_FAIL: ${{ inputs.DELETE_MDX_MISMATCHED_ERROR_ON_FAIL }}
        COMMIT_HASH: ${{ inputs.COMMIT_HASH }}
        POST_PULL_REQUEST_COMMENTS: ${{ inputs.POST_PULL_REQUEST_COMMENTS }}
        PULL_REQUEST_NUMBER: ${{ inputs.PULL_REQUEST_NUMBER }}
